name: Run chase tests

on: [push, pull_request]

jobs:
  run-tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            rev: nightly/nvim-linux-x86_64.tar.gz
          - os: ubuntu-22.04
            rev: v0.9.5/nvim-linux64.tar.gz
          - os: ubuntu-22.04
            rev: v0.10.4/nvim-linux-x86_64.tar.gz
          - os: ubuntu-22.04
            rev: v0.11.2/nvim-linux-x86_64.tar.gz
    steps:
      - uses: actions/checkout@v4
      - run: date +%F > todays-date
      - name: Restore cache for today's nightly.
        uses: actions/cache@v4
        with:
          path: _neovim
          key: ${{ runner.os }}-${{ matrix.rev }}-${{ hashFiles('todays-date') }} 
      - name: Prepare
        run: |
          test -d "${HOME}/_neovim" || {
            mkdir -p "${HOME}/_neovim"
            mkdir -p "${HOME}/_plugins/plenary"
            mkdir -p "${HOME}/work/neovim/neovim/.deps/usr/lib/lua/5.1"
            curl -sL "https://github.com/neovim/neovim/releases/download/${{ matrix.rev }}" | tar xzf - --strip-components=1 -C "${HOME}/_neovim"
            curl -sL "https://github.com/nvim-lua/plenary.nvim/archive/refs/tags/v0.1.4.tar.gz" | tar xzf - --strip-components=1 -C "${HOME}/_plugins/plenary"
            ln -s "${HOME}/_plugins/plenary/lua/plenary"
          }
      - name: Run tests
        run: |
          export PATH="${HOME}/_neovim/bin:${PATH}"
          export VIM="${HOME}/_neovim/share/nvim/runtime"
          nvim --version
          timeout --preserve-status -s QUIT 10 nvim --headless --noplugin -u scripts/minimal.vim -c "PlenaryBustedDirectory tests"
